# Generated by Django 5.1.15 on 2026-02-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0002_apirequestlog_chatmessage_chatsession_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpu_percent", models.FloatField()),
                ("memory_percent", models.FloatField()),
                ("disk_percent", models.FloatField()),
                ("bytes_sent", models.BigIntegerField(default=0)),
                ("bytes_recv", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
