# Generated by Django 5.1.15 on 2026-02-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0003_metricsnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_instance", models.CharField(default="n2-standard-4", max_length=100)),
                ("target_instance", models.CharField(default="n2-standard-4", max_length=100)),
                ("hours", models.IntegerField(default=720)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="OptimizationAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("scale_down", "Scale Down"), ("scale_up", "Scale Up"), ("keep", "Keep")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recommended", "Recommended"),
                            ("cooldown_skipped", "Cooldown Skipped"),
                            ("simulated_applied", "Simulated Applied"),
                        ],
                        default="recommended",
                        max_length=30,
                    ),
                ),
                ("current_instance", models.CharField(default="n2-standard-4", max_length=100)),
                ("target_instance", models.CharField(default="n2-standard-4", max_length=100)),
                ("reason", models.TextField(blank=True, default="")),
                ("cost_savings_usd", models.FloatField(default=0.0)),
                ("co2e_reduction_kg", models.FloatField(default=0.0)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="OptimizationPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("low", "Low"), ("balanced", "Balanced"), ("high", "High")],
                        default="balanced",
                        max_length=20,
                    ),
                ),
                ("optimization_enabled", models.BooleanField(default=True)),
                ("sample_interval_seconds", models.IntegerField(default=10)),
                ("cooldown_seconds", models.IntegerField(default=60)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
