# Generated by Django 5.1.15 on 2026-02-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0004_optimizationpolicy_optimizationaction_and_forecastsnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="optimizationpolicy",
            name="active_instance_name",
            field=models.CharField(default="hack-vm-1", max_length=120),
        ),
        migrations.AddField(
            model_name="optimizationpolicy",
            name="active_instance_zone",
            field=models.CharField(default="asia-south1-a", max_length=60),
        ),
    ]
